apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital-app
  namespace: praveen-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hospital-app
  template:
    metadata:
      labels:
        app: hospital-app
    spec:
      containers:
      - name: hospital-app
        image: 10kartikey/hospital-management-system-hospital-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          valueFrom:
            configMapRef:
              name: hospital-config
              key: MONGO_URI
          
        - name: PORT
          valueFrom:
            configMapRef:
              name: hospital-config
              key: PORT
        - name: NODE_ENV
          valueFrom:
            configMapRef:
              name: hospital-config
              key: NODE_ENV
        - name: SESSION_SECRET
          valueFrom:
            configMapRef:
              name: hospital-config
              key: SESSION_SECRET
        - name: JWT_SECRET
          valueFrom:
            configMapRef:
              name: hospital-config
              key: JWT_SECRET
        - name: ADMIN_USERNAME
          valueFrom:
            configMapRef:
              name: hospital-config
              key: ADMIN_USERNAME
        - name: ADMIN_PASSWORD
          valueFrom:
            configMapRef:
              name: hospital-config
              key: ADMIN_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: hospital-service
spec:
  selector:
    app: hospital-app
  ports:
  - port: 80
    targetPort: 5000
  type: ClusterIP
